version: '2.3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
     - GES_API_TOKEN
     - DISPLAY
    volumes:
    - /home/thomas/code/visual_genome:/app/visual_genome
    - /home/thomas/code/vg_demo:/app
    - /etc/group:/etc/group:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - /etc/sudoers.d:/etc/sudoers.d:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  detectron:
    image: "odellus/detectron_srvc:version9"
    runtime: nvidia
    ports:
     - "8085:8085"
  scene_graph:
    image: "odellus/sg_srvc:version9"
    runtime: nvidia
    ports:
     - "8080:8080"
