version: '2.3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
     - GES_API_TOKEN
    volumes:
    # CHANGE THESE THEY WILL NOT WORK ELSEWHERE
    - /home/thomas/code/visual_genome:/app/visual_genome
  detectron:
    image: "odellus/detectron_srvc:version9"
    runtime: nvidia
    ports:
     - "8085:8085"
  scene_graph:
    image: "odellus/sg_srvc:version9"
    runtime: nvidia
    ports:
     - "8080:8080"
